-- MySQL Script generated by MySQL Workbench
-- 09/28/16 22:18:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ceidin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ceidin` ;

-- -----------------------------------------------------
-- Schema ceidin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ceidin` DEFAULT CHARACTER SET utf8 ;
USE `ceidin` ;

-- -----------------------------------------------------
-- Table `ceidin`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`persona` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_1` TEXT NOT NULL,
  `nombre_2` TEXT NULL,
  `apellido_1` TEXT NOT NULL,
  `apellido_2` TEXT NULL,
  `cedula` DECIMAL(10,0) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` TEXT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`cargo` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`cargo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`empleado` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`empleado` (
  `id_persona` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_persona`, `id_cargo`),
  INDEX `fk_empleado_cargo1_idx` (`id_cargo` ASC),
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleado_cargo1`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `ceidin`.`cargo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`parentesco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`parentesco` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`parentesco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`representante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`representante` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`representante` (
  `id_persona` INT NOT NULL,
  `id_parentesco` INT NOT NULL,
  `telefono_casa` TEXT NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_representante_parentesco1_idx` (`id_parentesco` ASC),
  CONSTRAINT `fk_representante_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_representante_parentesco1`
    FOREIGN KEY (`id_parentesco`)
    REFERENCES `ceidin`.`parentesco` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`tipo_embarazo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`tipo_embarazo` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`tipo_embarazo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`tipo_parto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`tipo_parto` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`tipo_parto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`prenatal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`prenatal` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`prenatal` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_embarazo` INT NOT NULL,
  `id_tipo_parto` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_prenatal_tipo_embarazo1_idx` (`id_tipo_embarazo` ASC),
  INDEX `fk_prenatal_tipo_parto1_idx` (`id_tipo_parto` ASC),
  CONSTRAINT `fk_prenatal_tipo_embarazo1`
    FOREIGN KEY (`id_tipo_embarazo`)
    REFERENCES `ceidin`.`tipo_embarazo` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_prenatal_tipo_parto1`
    FOREIGN KEY (`id_tipo_parto`)
    REFERENCES `ceidin`.`tipo_parto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_salud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_salud` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_salud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_prenatal` INT NOT NULL,
  `problema_durante_parto` TEXT NOT NULL,
  `desarrollo_primer_anio` TEXT NOT NULL,
  `desarrollo_posterior` TEXT NOT NULL,
  `problema_de_lenguaje` TEXT NOT NULL,
  `edad_control_esfinteres` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_antecedente_salud_prenatal1_idx` (`id_prenatal` ASC),
  CONSTRAINT `fk_antecedente_salud_prenatal1`
    FOREIGN KEY (`id_prenatal`)
    REFERENCES `ceidin`.`prenatal` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`procedencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`procedencia` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`procedencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`vivienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`vivienda` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`vivienda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`religion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`religion` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`religion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`situacion_pareja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`situacion_pareja` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`situacion_pareja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_familiar` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_familiar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_vivienda` INT NOT NULL,
  `id_religion` INT NOT NULL,
  `id_situacion_pareja` INT NOT NULL,
  `nro_hermanos` INT NOT NULL COMMENT '	',
  `lugar_grupo_familiar` TEXT NOT NULL,
  `cuidado_en_casa_por` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_antecedente_familiar_vivienda1_idx` (`id_vivienda` ASC),
  INDEX `fk_antecedente_familiar_religion1_idx` (`id_religion` ASC),
  INDEX `fk_antecedente_familiar_situacion_pareja1_idx` (`id_situacion_pareja` ASC),
  CONSTRAINT `fk_antecedente_familiar_vivienda1`
    FOREIGN KEY (`id_vivienda`)
    REFERENCES `ceidin`.`vivienda` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_familiar_religion1`
    FOREIGN KEY (`id_religion`)
    REFERENCES `ceidin`.`religion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_familiar_situacion_pareja1`
    FOREIGN KEY (`id_situacion_pareja`)
    REFERENCES `ceidin`.`situacion_pareja` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`alumno` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`alumno` (
  `id_persona` INT NOT NULL,
  `id_antecedente_familiar` INT NOT NULL,
  `id_antecedente_salud` INT NOT NULL,
  `id_procedencia` INT NOT NULL,
  `lugar_nacmiento` TEXT NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_alumno_antecedente_salud1_idx` (`id_antecedente_salud` ASC),
  INDEX `fk_alumno_procedencia1_idx` (`id_procedencia` ASC),
  INDEX `fk_alumno_antecedente_familiar1_idx` (`id_antecedente_familiar` ASC),
  CONSTRAINT `fk_alumno_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_antecedente_salud1`
    FOREIGN KEY (`id_antecedente_salud`)
    REFERENCES `ceidin`.`antecedente_salud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_procedencia1`
    FOREIGN KEY (`id_procedencia`)
    REFERENCES `ceidin`.`procedencia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_antecedente_familiar1`
    FOREIGN KEY (`id_antecedente_familiar`)
    REFERENCES `ceidin`.`antecedente_familiar` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`anio_escolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`anio_escolar` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`anio_escolar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`seccion` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`seccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `id_anio_escolar` INT NOT NULL,
  `id_docente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_seccion_anio_escolar1_idx` (`id_anio_escolar` ASC),
  INDEX `fk_seccion_empleado1_idx` (`id_docente` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC, `id_anio_escolar` ASC),
  CONSTRAINT `fk_seccion_anio_escolar1`
    FOREIGN KEY (`id_anio_escolar`)
    REFERENCES `ceidin`.`anio_escolar` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seccion_empleado1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`turno` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`turno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`medida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`medida` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`medida` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `talla` FLOAT NOT NULL,
  `peso` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`otros_datos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`otros_datos` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`otros_datos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `medida_al_entrar` INT NOT NULL,
  `medida_al_salir` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_otros_datos_medida1_idx` (`medida_al_entrar` ASC),
  INDEX `fk_otros_datos_medida2_idx` (`medida_al_salir` ASC),
  CONSTRAINT `fk_otros_datos_medida1`
    FOREIGN KEY (`medida_al_entrar`)
    REFERENCES `ceidin`.`medida` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_otros_datos_medida2`
    FOREIGN KEY (`medida_al_salir`)
    REFERENCES `ceidin`.`medida` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`inscripcion` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`inscripcion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_seccion` INT NOT NULL,
  `id_representante` INT NOT NULL,
  `id_turno` INT NOT NULL,
  `id_alumno` INT NOT NULL,
  `id_otros_datos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscripcion_seccion1_idx` (`id_seccion` ASC),
  INDEX `fk_inscripcion_representante1_idx` (`id_representante` ASC),
  INDEX `fk_inscripcion_turno1_idx` (`id_turno` ASC),
  INDEX `fk_inscripcion_alumno1_idx` (`id_alumno` ASC),
  INDEX `fk_inscripcion_otros_datos1_idx` (`id_otros_datos` ASC),
  CONSTRAINT `fk_inscripcion_seccion1`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `ceidin`.`seccion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscripcion_representante1`
    FOREIGN KEY (`id_representante`)
    REFERENCES `ceidin`.`representante` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscripcion_turno1`
    FOREIGN KEY (`id_turno`)
    REFERENCES `ceidin`.`turno` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscripcion_alumno1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `ceidin`.`alumno` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscripcion_otros_datos1`
    FOREIGN KEY (`id_otros_datos`)
    REFERENCES `ceidin`.`otros_datos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`retiro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`retiro` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`retiro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_inscripcion` INT NOT NULL,
  `atentido_por` INT NOT NULL,
  `retirado_por` INT NOT NULL,
  `motivo` TEXT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_retiro_inscripcion1_idx` (`id_inscripcion` ASC),
  INDEX `fk_retiro_empleado1_idx` (`atentido_por` ASC),
  INDEX `fk_retiro_persona1_idx` (`retirado_por` ASC),
  CONSTRAINT `fk_retiro_inscripcion1`
    FOREIGN KEY (`id_inscripcion`)
    REFERENCES `ceidin`.`inscripcion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_retiro_empleado1`
    FOREIGN KEY (`atentido_por`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_retiro_persona1`
    FOREIGN KEY (`retirado_por`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`documento_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`documento_identificacion` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`documento_identificacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`dia_laborable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`dia_laborable` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`dia_laborable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_anio_escolar` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dia_laborable_anio_escolar1_idx` (`id_anio_escolar` ASC),
  CONSTRAINT `fk_dia_laborable_anio_escolar1`
    FOREIGN KEY (`id_anio_escolar`)
    REFERENCES `ceidin`.`anio_escolar` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`juego` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`juego` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`vacuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`vacuna` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`vacuna` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`medicamento_fiebre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`medicamento_fiebre` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`medicamento_fiebre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`enfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`enfermedad` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`enfermedad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`alergia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`alergia` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`alergia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`estatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`estatus` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`estatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`usuario` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`usuario` (
  `id_persona` INT NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `correo` VARCHAR(255) NOT NULL,
  `id_estatus` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_usuario_id_estatus_id_estatus1_idx` (`id_estatus` ASC),
  CONSTRAINT `fk_usuario_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_id_estatus_id_estatus1`
    FOREIGN KEY (`id_estatus`)
    REFERENCES `ceidin`.`estatus` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`alumno_juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`alumno_juego` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`alumno_juego` (
  `id_alumno` INT NOT NULL,
  `id_juego` INT NOT NULL,
  PRIMARY KEY (`id_alumno`, `id_juego`),
  INDEX `fk_juego_has_alumno_alumno1_idx` (`id_alumno` ASC),
  INDEX `fk_juego_has_alumno_juego1_idx` (`id_juego` ASC),
  CONSTRAINT `fk_juego_has_alumno_juego1`
    FOREIGN KEY (`id_juego`)
    REFERENCES `ceidin`.`juego` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_juego_has_alumno_alumno1`
    FOREIGN KEY (`id_alumno`)
    REFERENCES `ceidin`.`alumno` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_salud_alergia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_salud_alergia` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_salud_alergia` (
  `id_antecedente_salud` INT NOT NULL,
  `id_alergia` INT NOT NULL,
  PRIMARY KEY (`id_antecedente_salud`, `id_alergia`),
  INDEX `fk_antecedente_salud_has_alergia_alergia1_idx` (`id_alergia` ASC),
  INDEX `fk_antecedente_salud_has_alergia_antecedente_salud1_idx` (`id_antecedente_salud` ASC),
  CONSTRAINT `fk_antecedente_salud_has_alergia_antecedente_salud1`
    FOREIGN KEY (`id_antecedente_salud`)
    REFERENCES `ceidin`.`antecedente_salud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_salud_has_alergia_alergia1`
    FOREIGN KEY (`id_alergia`)
    REFERENCES `ceidin`.`alergia` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_salud_enfermedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_salud_enfermedad` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_salud_enfermedad` (
  `id_antecedente_salud` INT NOT NULL,
  `id_enfermedad` INT NOT NULL,
  PRIMARY KEY (`id_antecedente_salud`, `id_enfermedad`),
  INDEX `fk_antecedente_salud_has_enfermedad_enfermedad1_idx` (`id_enfermedad` ASC),
  INDEX `fk_antecedente_salud_has_enfermedad_antecedente_salud1_idx` (`id_antecedente_salud` ASC),
  CONSTRAINT `fk_antecedente_salud_has_enfermedad_antecedente_salud1`
    FOREIGN KEY (`id_antecedente_salud`)
    REFERENCES `ceidin`.`antecedente_salud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_salud_has_enfermedad_enfermedad1`
    FOREIGN KEY (`id_enfermedad`)
    REFERENCES `ceidin`.`enfermedad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_salud_vacuna`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_salud_vacuna` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_salud_vacuna` (
  `id_antecedente_salud` INT NOT NULL,
  `id_vacuna` INT NOT NULL,
  PRIMARY KEY (`id_antecedente_salud`, `id_vacuna`),
  INDEX `fk_antecedente_salud_has_vacuna_vacuna1_idx` (`id_vacuna` ASC),
  INDEX `fk_antecedente_salud_has_vacuna_antecedente_salud1_idx` (`id_antecedente_salud` ASC),
  CONSTRAINT `fk_antecedente_salud_has_vacuna_antecedente_salud1`
    FOREIGN KEY (`id_antecedente_salud`)
    REFERENCES `ceidin`.`antecedente_salud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_salud_has_vacuna_vacuna1`
    FOREIGN KEY (`id_vacuna`)
    REFERENCES `ceidin`.`vacuna` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`nacionalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`nacionalidad` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`nacionalidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`familiar` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`familiar` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `id_parentesco` INT NOT NULL,
  `grado_instruccion` TEXT NOT NULL,
  `ocupacion` TEXT NOT NULL,
  `id_nacionalidad` INT NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_familiar_parentesco1_idx` (`id_parentesco` ASC),
  INDEX `fk_familiar_nacionalidad1_idx` (`id_nacionalidad` ASC),
  CONSTRAINT `fk_familiar_persona1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `ceidin`.`persona` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_familiar_parentesco1`
    FOREIGN KEY (`id_parentesco`)
    REFERENCES `ceidin`.`parentesco` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_familiar_nacionalidad1`
    FOREIGN KEY (`id_nacionalidad`)
    REFERENCES `ceidin`.`nacionalidad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_familiar_familiar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_familiar_familiar` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_familiar_familiar` (
  `id_antecedente_familiar` INT NOT NULL,
  `id_familiar` INT NOT NULL,
  PRIMARY KEY (`id_antecedente_familiar`, `id_familiar`),
  INDEX `fk_antecedente_familiar_has_familiar_familiar1_idx` (`id_familiar` ASC),
  INDEX `fk_antecedente_familiar_has_familiar_antecedente_familiar1_idx` (`id_antecedente_familiar` ASC),
  CONSTRAINT `fk_antecedente_familiar_has_familiar_antecedente_familiar1`
    FOREIGN KEY (`id_antecedente_familiar`)
    REFERENCES `ceidin`.`antecedente_familiar` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_familiar_has_familiar_familiar1`
    FOREIGN KEY (`id_familiar`)
    REFERENCES `ceidin`.`familiar` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`antecedente_salud_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`antecedente_salud_medicamento` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`antecedente_salud_medicamento` (
  `id_antecedente_salud` INT NOT NULL,
  `id_medicamento` INT NOT NULL,
  PRIMARY KEY (`id_antecedente_salud`, `id_medicamento`),
  INDEX `fk_antecedente_salud_has_medicamento_medicamento1_idx` (`id_medicamento` ASC),
  INDEX `fk_antecedente_salud_has_medicamento_antecedente_salud1_idx` (`id_antecedente_salud` ASC),
  CONSTRAINT `fk_antecedente_salud_has_medicamento_antecedente_salud1`
    FOREIGN KEY (`id_antecedente_salud`)
    REFERENCES `ceidin`.`antecedente_salud` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_antecedente_salud_has_medicamento_medicamento1`
    FOREIGN KEY (`id_medicamento`)
    REFERENCES `ceidin`.`medicamento_fiebre` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`inscripcion_documento_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`inscripcion_documento_identificacion` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`inscripcion_documento_identificacion` (
  `inscripcion_id` INT NOT NULL,
  `documento_identificacion_id` INT NOT NULL,
  PRIMARY KEY (`inscripcion_id`, `documento_identificacion_id`),
  INDEX `fk_inscripcion_has_documento_identificacion_documento_ident_idx` (`documento_identificacion_id` ASC),
  INDEX `fk_inscripcion_has_documento_identificacion_inscripcion1_idx` (`inscripcion_id` ASC),
  CONSTRAINT `fk_inscripcion_has_documento_identificacion_inscripcion1`
    FOREIGN KEY (`inscripcion_id`)
    REFERENCES `ceidin`.`inscripcion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscripcion_has_documento_identificacion_documento_identif1`
    FOREIGN KEY (`documento_identificacion_id`)
    REFERENCES `ceidin`.`documento_identificacion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`acta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`acta` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`acta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_acta` VARCHAR(255) NOT NULL,
  `id_sae` INT NOT NULL,
  `id_directivo` INT NOT NULL,
  `id_docente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_acta_empleado1_idx` (`id_sae` ASC),
  INDEX `fk_acta_empleado2_idx` (`id_directivo` ASC),
  INDEX `fk_acta_empleado3_idx` (`id_docente` ASC),
  UNIQUE INDEX `numero_acta_UNIQUE` (`numero_acta` ASC),
  CONSTRAINT `fk_acta_empleado1`
    FOREIGN KEY (`id_sae`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_acta_empleado2`
    FOREIGN KEY (`id_directivo`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_acta_empleado3`
    FOREIGN KEY (`id_docente`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`unidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`unidad` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`unidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`producto` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `id_unidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_unidad1_idx` (`id_unidad` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC, `id_unidad` ASC),
  CONSTRAINT `fk_producto_unidad1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `ceidin`.`unidad` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`acta_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`acta_producto` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`acta_producto` (
  `acta_id` INT NOT NULL,
  `id_producto` INT NOT NULL,
  PRIMARY KEY (`acta_id`, `id_producto`),
  INDEX `fk_acta_has_producto_producto1_idx` (`id_producto` ASC),
  INDEX `fk_acta_has_producto_acta1_idx` (`acta_id` ASC),
  CONSTRAINT `fk_acta_has_producto_acta1`
    FOREIGN KEY (`acta_id`)
    REFERENCES `ceidin`.`acta` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_acta_has_producto_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `ceidin`.`producto` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`rol` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `descripcion` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`rol_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`rol_usuario` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`rol_usuario` (
  `id_rol` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_usuario`),
  INDEX `fk_rol_has_usuario_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_rol_has_usuario_rol1_idx` (`id_rol` ASC),
  CONSTRAINT `fk_rol_has_usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `ceidin`.`rol` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rol_has_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `ceidin`.`usuario` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ceidin`.`asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ceidin`.`asistencia` ;

CREATE TABLE IF NOT EXISTS `ceidin`.`asistencia` (
  `id_empleado` INT NOT NULL,
  `id_dia_laborable` INT NOT NULL,
  PRIMARY KEY (`id_empleado`, `id_dia_laborable`),
  INDEX `fk_empleado_has_dia_laborable_dia_laborable1_idx` (`id_dia_laborable` ASC),
  INDEX `fk_empleado_has_dia_laborable_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_empleado_has_dia_laborable_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `ceidin`.`empleado` (`id_persona`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleado_has_dia_laborable_dia_laborable1`
    FOREIGN KEY (`id_dia_laborable`)
    REFERENCES `ceidin`.`dia_laborable` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
